repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: no-commit-to-branch
      - id: check-added-large-files
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        args: ["--unsafe"]

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.4
    hooks:
      - id: poetry-check
      - id: poetry-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        types_or: [python, pyi]
        args: ["--fix"]
      - id: ruff-format
        types_or: [python, pyi]

  - repo: local
    hooks:
    - id: lint
      name: Lint
      entry: poetry run mypy --config-file pyproject.toml .
      types: [python]
      language: system
      pass_filenames: false
